### ISSUE TITLE
Web live view layouts are not saved across sessions

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-apps#587]
> Theoretically I could use http/liveview for any use case but every time I leave the http LiveView all my selected cameras are forgotten and I need to add them again

**Comment by curtishall** [comment]
https://forums.bluecherrydvr.com/t/liveview-does-not-remember-camera-selection/744

**Comment by curtishall** [comment]
This feature used to work with MJPEG feeds, however by switching to HLS feeds they auth key expires and the feeds break.  Some thoughts:

We need to:

- Modify the layout to capture the deviceId for each camera instead of the HLS URL.
- Send this modified layout data, which includes camera deviceId, to the server and save it in the database.
- Regenerate HLS URLs when loading the layout (When a layout is loaded, use the saved camera identifiers to dynamically generate HLS URLs using createHlsLink)

**Comment by netforce** [comment]
Layout is not saved

```
==> /var/log/nginx/bluecherry-error.log <==
2025/03/09 13:00:16 [error] 26206#26206: *8351 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Data too long for column 'layout' at row 1 in /usr/share/bluecherry/www/lib/lib.php:245
Stack trace:
#0 /usr/share/bluecherry/www/lib/lib.php(245): mysqli_query()
#1 /usr/share/bluecherry/www/lib/lib.php(266): database->fetchAll()
#2 /usr/share/bluecherry/www/ajax/layouts.php(52): data::query()
#3 /usr/share/bluecherry/www/ajax/layouts.php(15): layouts->newLayout()
#4 /usr/share/bluecherry/www/ajax/liveview.php(16): layouts->postData()
#5 /usr/share/bluecherry/www/lib/Controller.php(119): liveview->postLayouts()
#6 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#7 /usr/share/bluecherry/www/index.php(16): Route->start()
#8 {main}
  thrown in /usr/share/bluecherry/www/lib/lib.php on line 245" while reading response header from upstream, client: 192.168.10.59, server: , request: "POST /liveview/layouts HTTP/1.1", upstream: "fastcgi://unix:/etc/alternatives/php-fpm.sock:", host: "192.168.10.73:7001", referrer: "https://192.168.10.73:7001/liveview"
```

**Comment by curtishall** [comment]
Can you run this command?

```
mysql -D bluecherry -u bluecherry -p -e "ALTER TABLE userLayouts MODIFY COLUMN layout TEXT;"
```

**Comment by netforce** [comment]
yes, and executed;

```
MariaDB [bluecherry]> describe userLayouts;
+-------------+-------------+------+-----+---------+----------------+
| Field       | Type        | Null | Key | Default | Extra          |
+-------------+-------------+------+-----+---------+----------------+
| id          | int(11)     | NO   | PRI | NULL    | auto_increment |
| user_id     | int(11)     | YES  |     | NULL    |                |
| layout_name | varchar(50) | YES  |     | NULL    |                |
| layout      | text        | YES  |     | NULL    |                |
+-------------+-------------+------+-----+---------+----------------+
```

```
MariaDB [bluecherry]> delete from userLayouts;
Query OK, 3 rows affected (0.003 sec)
```

Brave browser: added a view, with one cam
```
2025/03/10 20:38:09 [error] 1548#1548: *429 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli_fetch_all(): Argument #1 ($result) must be of type mysqli_result, bool given in /usr/share/bluecherry/www/lib/lib.php:248
Stack trace:
#0 /usr/share/bluecherry/www/lib/lib.php(248): mysqli_fetch_all()
#1 /usr/share/bluecherry/www/lib/lib.php(266): database->fetchAll()
#2 /usr/share/bluecherry/www/ajax/layouts.php(52): data::query()
#3 /usr/share/bluecherry/www/ajax/layouts.php(15): layouts->newLayout()
#4 /usr/share/bluecherry/www/ajax/liveview.php(16): layouts->postData()
#5 /usr/share/bluecherry/www/lib/Controller.php(119): liveview->postLayouts()
#6 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#7 /usr/share/bluecherry/www/index.php(16): Route->start()
#8 {main}
  thrown in /usr/share/bluecherry/www/lib/lib.php on line 248" while reading response header from upstream, client: 192.168.10.59, server: , request: "POST /liveview/layouts HTTP/1.1", upstream: "fastcgi://unix:/etc/alternatives/php-fpm.sock:", host: "192.168.10.73:7001", referrer: "https://192.168.10.73:7001/liveview"
```
```
MariaDB [bluecherry]> select * from userLayouts;
+----+---------+-------------+--------------------------------------------------------------------------------------------+
| id | user_id | layout_name | layout                                                                                     |
+----+---------+-------------+--------------------------------------------------------------------------------------------+
|  8 |       1 | OneCam      | {\"live_view11\":\"blob:https://192.168.10.73:7001/2c4fd98e-98bc-458f-8749-8561c9d25294\"} |
+----+---------+-------------+--------------------------------------------------------------------------------------------+
```

Brave/Firefox browser: Loading the new view does not work
```
2025/03/10 20:39:29 [error] 1545#1545: *426 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "{OneCam}" in /usr/share/bluecherry/www/ajax/layouts.php on line 72" while reading response header from upstream, client: 192.168.10.59, server: , request: "POST /liveview/layouts HTTP/1.1", upstream: "fastcgi://unix:/etc/alternatives/php-fpm.sock:", host: "192.168.10.73:7001", referrer: "https://192.168.10.73:7001/liveview"
```

**Comment by netforce** [comment]
same issue with only firefox;

```
2025/03/10 20:41:35 [error] 1548#1548: *572 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: mysqli_fetch_all(): Argument #1 ($result) must be of type mysqli_result, bool given in /usr/share/bluecherry/www/lib/lib.php:248
Stack trace:
#0 /usr/share/bluecherry/www/lib/lib.php(248): mysqli_fetch_all()
#1 /usr/share/bluecherry/www/lib/lib.php(266): database->fetchAll()
#2 /usr/share/bluecherry/www/ajax/layouts.php(52): data::query()
#3 /usr/share/bluecherry/www/ajax/layouts.php(15): layouts->newLayout()
#4 /usr/share/bluecherry/www/ajax/liveview.php(16): layouts->postData()
#5 /usr/share/bluecherry/www/lib/Controller.php(119): liveview->postLayouts()
#6 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#7 /usr/share/bluecherry/www/index.php(16): Route->start()
#8 {main}
  thrown in /usr/share/bluecherry/www/lib/lib.php on line 248" while reading response header from upstream, client: 192.168.10.59, server: , request: "POST /liveview/layouts HTTP/1.1", upstream: "fastcgi://unix:/etc/alternatives/php-fpm.sock:", host: "192.168.10.73:7001", referrer: "https://192.168.10.73:7001/liveview"


2025/03/10 20:41:54 [error] 1548#1548: *572 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "{TwoCamFirefox}" in /usr/share/bluecherry/www/ajax/layouts.php on line 72" while reading response header from upstream, client: 192.168.10.59, server: , request: "POST /liveview/layouts HTTP/1.1", upstream: "fastcgi://unix:/etc/alternatives/php-fpm.sock:", host: "192.168.10.73:7001", referrer: "https://192.168.10.73:7001/liveview"

```
