### ISSUE TITLE
Devices in bluecherry build

### ISSUE THREAD

**Issue by haadiali72** [bluecherrydvr/bluecherry-apps#609]
I am not sure if this due to some build error or an issue with this release but please provide support. I cloned the bluecherry-apps repo and ran the build natively. The devices page gives a http error 500

![image](https://github.com/bluecherrydvr/bluecherry-apps/assets/75501297/1d7eaabc-7489-4100-b857-b56c7a5aa08e)
 

https://github.com/bluecherrydvr/bluecherry-apps/assets/75501297/7156ad05-290a-4d85-8261-888364407498

**Comment by curtishall** [comment]
Which branch did you build on? 'master'?

What does this show:

tail -n 100 /var/log/nginx/bluecherry-error.log

**Comment by haadiali72** [comment]
thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/activeusers"
2023/07/24 22:18:35 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/activeusers"
2023/07/24 22:18:35 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/activeusers"
2023/07/24 22:18:35 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/activeusers"
2023/07/24 22:18:46 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Warning:  Cannot assign an empty string to a string offset in /usr/sha                                                                                                             re/bluecherry/www/template/ajax/users.php on line 46PHP message: PHP Warning:  i                                                                                                             mplode(): Invalid arguments passed in /usr/share/bluecherry/www/template/ajax/us                                                                                                             ers.php on line 48" while reading response header from upstream, client: 192.168                                                                                                             .1.76, server: , request: "GET /users?type=ajax_content HTTP/1.1", upstream: "fa                                                                                                             stcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "192.168.1.5:7001", referrer:                                                                                                              "https://192.168.1.5:7001/activeusers"
2023/07/24 22:18:49 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices?type=ajax_content HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.                                                                                                             4-fpm.sock:", host: "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/user                                                                                                             s"
2023/07/24 22:18:49 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:18:56 [error] 107536#107536: *712 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Warning:  Cannot assign an empty string to a string offset in /usr/sha                                                                                                             re/bluecherry/www/template/ajax/users.php on line 46PHP message: PHP Warning:  i                                                                                                             mplode(): Invalid arguments passed in /usr/share/bluecherry/www/template/ajax/us                                                                                                             ers.php on line 48" while reading response header from upstream, client: 192.168                                                                                                             .1.76, server: , request: "GET /users HTTP/1.1", upstream: "fastcgi://unix:/var/                                                                                                             run/php/php7.4-fpm.sock:", host: "192.168.1.5:7001"
2023/07/24 22:19:28 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices?type=ajax_content HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.                                                                                                             4-fpm.sock:", host: "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/user                                                                                                             s"
2023/07/24 22:19:28 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:19:30 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:19:30 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:19:31 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:19:31 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:19:32 [error] 107536#107536: *710 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Warning:  Cannot assign an empty string to a string offset in /usr/sha                                                                                                             re/bluecherry/www/template/ajax/users.php on line 46PHP message: PHP Warning:  i                                                                                                             mplode(): Invalid arguments passed in /usr/share/bluecherry/www/template/ajax/us                                                                                                             ers.php on line 48" while reading response header from upstream, client: 192.168                                                                                                             .1.76, server: , request: "GET /users HTTP/1.1", upstream: "fastcgi://unix:/var/                                                                                                             run/php/php7.4-fpm.sock:", host: "192.168.1.5:7001"
2023/07/24 22:21:17 [error] 107536#107536: *711 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Warning:  Cannot assign an empty string to a string offset in /usr/sha                                                                                                             re/bluecherry/www/template/ajax/users.php on line 46PHP message: PHP Warning:  i                                                                                                             mplode(): Invalid arguments passed in /usr/share/bluecherry/www/template/ajax/us                                                                                                             ers.php on line 48" while reading response header from upstream, client: 192.168                                                                                                             .1.76, server: , request: "GET /users HTTP/1.1", upstream: "fastcgi://unix:/var/                                                                                                             run/php/php7.4-fpm.sock:", host: "192.168.1.5:7001"
2023/07/24 22:22:06 [error] 107538#107538: *835 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices?type=ajax_content HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.                                                                                                             4-fpm.sock:", host: "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/user                                                                                                             s"
2023/07/24 22:22:06 [error] 107538#107538: *836 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Fatal error:  Uncaught Error: Call to undefined method devices::reqJSO                                                                                                             N() in /usr/share/bluecherry/www/ajax/devices.php:33
Stack trace:
#0 /usr/share/bluecherry/www/lib/Controller.php(137): devices->getData()
#1 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#2 /usr/share/bluecherry/www/index.php(16): Route->start()
#3 {main}
  thrown in /usr/share/bluecherry/www/ajax/devices.php on line 33" while reading                                                                                                              response header from upstream, client: 192.168.1.76, server: , request: "GET /d                                                                                                             evices HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host                                                                                                             : "192.168.1.5:7001", referrer: "https://192.168.1.5:7001/users"
2023/07/24 22:22:08 [error] 107538#107538: *836 FastCGI sent in stderr: "PHP mes                                                                                                             sage: PHP Warning:  Cannot assign an empty string to a string offset in /usr/sha                                                                                                             re/bluecherry/www/template/ajax/users.php on line 46PHP message: PHP Warning:  i                                                                                                             mplode(): Invalid arguments passed in /usr/share/bluecherry/www/template/ajax/us                                                                                                             ers.php on line 48" while reading response header from upstream, client: 192.168                                                                                                             .1.76, server: , request: "GET /users HTTP/1.1", upstream: "fastcgi://unix:/var/                                                                                                             run/php/php7.4-fpm.sock:", host: "192.168.1.5:7001"

**Comment by haadiali72** [comment]
Yes I built it on master branch

**Comment by curtishall** [comment]
Okay, I see the problem...there was code that was submitted to master that wasn't finished yet.

Checkout the 'new_api' branch, that has the latest ffmpeg lib changes and before the commit.
```
git checkout new_api
```
then build.
